name: Java CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3️⃣ Build with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t msc-java-microservice .

      # 5️⃣ Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 6️⃣ Push Docker image to GHCR
      - name: Push Docker image
        run: |
          docker tag msc-java-microservice ghcr.io/${{ github.repository_owner }}/msc-java-microservice:latest
          docker push ghcr.io/${{ github.repository_owner }}/msc-java-microservice:latest
